### ISSUE TITLE
some questions 

### ISSUE THREAD

**Issue by ka1n4t** [stamparm/DSXS#10]
Hello stamparm! I have some questions when I read your project.
1. Why you using LARGER_CHAR_POOL&SMALLER_CHAR_POOL? why not just one larger pool?
2. In line 63&64, why adding a single quote before the prefix when using LARGER_CHAR_POOL?

that's all, look forward to your reply, thanks.

**Comment by stamparm** [comment]
Hi.

1) Because in some situations, WAFs/protection|filtering mechanisms/IPSs/etc. are really paranoid and don't like all those malicious chars found in LARGER_CHAR_POOL. By using only `<` and `>` inside `SMALLER_CHAR_POOL` DSXS tries to create not so obvious/malicious payload (e.g. `?id=1raqwx><khwyj`)
2) If there is a SQLi, to try to provoke XSS through it (too). Thing is that that same single-quote will be a starting point of invalid SQL part and if DBMS error is turned on, the whole deliberately invalid payload will be reflected back in form of DBMS error message. Basically, without a single quote, there are SQLi cases where you won't see the WHOLE payload reflected back

Bye

**Comment by ka1n4t** [comment]
Good idea! Thanks for your help:]]
